name: API availability

on:
  push:
    branches:
      - master
  schedule:
    - cron:  "0 00 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check API availability
      run: ./scripts/check-api.sh
