name: Post message

on:
  schedule:
    - cron:  "0 6 * * 1-5"

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Post message
      env:
        WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
      run: npm start
